In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.14581939, 0.68000323, 0.57014398, 0.75079989, 0.40684871])

In [22]:
np.random.randn(2,2,2)

array([[[0.09553598, 0.23262353],
        [0.57625957, 0.63806981]],

       [[0.66103386, 0.18004576],
        [0.70117079, 0.93734281]]])

In [25]:
np.random.randint(1,100,10)

array([ 2, 46, 30, 62, 24, 58, 24, 48,  3, 79], dtype=int32)

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[8]

np.int64(8)

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [34]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [35]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [36]:

arr[0:5]

array([0, 1, 2, 3, 4])

In [37]:
arr_2d = np.array([[5,12,34],[34,56,77],[45,78,9]])

In [38]:
arr_2d

array([[ 5, 12, 34],
       [34, 56, 77],
       [45, 78,  9]])

In [40]:
arr_2d[1:]

array([[34, 56, 77],
       [45, 78,  9]])

In [42]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
boolean_arr = arr >5

In [46]:
arr[boolean_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr >4]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[arr >3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [55]:
np.ones(11)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [56]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [57]:
np.array([[[0,1,2],[3,4,5],[6,7,8]]])

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.random.rand(25)

array([0.74879859, 0.67740516, 0.0783662 , 0.61572035, 0.6391122 ,
       0.86752047, 0.24153938, 0.65758311, 0.05061422, 0.68984645,
       0.33280289, 0.42171044, 0.63272914, 0.67881776, 0.4251402 ,
       0.733561  , 0.85359148, 0.62886413, 0.13140342, 0.70842573,
       0.72482651, 0.70878644, 0.13671132, 0.99098448, 0.67072803])