In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.14581939, 0.68000323, 0.57014398, 0.75079989, 0.40684871])

In [22]:
np.random.randn(2,2,2)

array([[[0.09553598, 0.23262353],
        [0.57625957, 0.63806981]],

       [[0.66103386, 0.18004576],
        [0.70117079, 0.93734281]]])

In [25]:
np.random.randint(1,100,10)

array([ 2, 46, 30, 62, 24, 58, 24, 48,  3, 79], dtype=int32)

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])